version: '3.8'
services:
  wordpress:
   image: wordpress:latest
   ports:
    - "8080:80"
   environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: wp_user
    WORDPRESS_DB_PASSWORD: wp_pass
    WORDPRESS_DB_NAME: wp_database
   depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data: